### ISSUE TITLE
Improved inventory management

### ISSUE THREAD

**Issue by Borkason** [rm-code/On-The-Roadside#78]
Currently I have to move stuff around in my inventory by clicking on the item to pick it up and clicking again to place the item.

It would be nice if, for example, I could right-click on an item that is in a chest or on the ground, and it gets placed in my inventory and vice versa.

It would also be nice if I could drag-and-drop items by left-clicking them without releasing the mouse button.

**Comment by rm-code** [comment]
> It would be nice if, for example, I could right-click on an item that is in a chest or on the ground, and it gets placed in my inventory and vice versa.

You mean just by clicking once on the item it should be placed in the rucksack? Sounds like a great time saver!

(Ref #50)

**Comment by rm-code** [comment]
Merged the suggestions into #50.
