### ISSUE TITLE
Requested body template (human) doesn't exist!

### ISSUE THREAD

**Issue by Borkason** [rm-code/On-The-Roadside#91]
> Error: src/characters/body/BodyFactory.lua:160: Requested body template (human) doesn't exist!
> stack traceback:
>         src/characters/body/BodyFactory.lua:160: in function 'create'
>         src/characters/Character.lua:51: in function 'new'
>         src/characters/CharacterFactory.lua:77: in function 'newCharacter'
>         src/characters/Factions.lua:69: in function 'spawnCharacters'
>         src/characters/Factions.lua:121: in function 'spawnCharacters'
>         src/Game.lua:80: in function 'init'
>         src/screens/MainScreen.lua:49: in function 'init'
>         lib/screenmanager/ScreenManager.lua:110: in function 'push'
>         lib/screenmanager/ScreenManager.lua:68: in function 'init'
>         main.lua:40: in function 'load'
>         [string "boot.lua"]:440: in function <[string "boot.lua"]:436>
>         [C]: in function 'xpcall'

**Comment by rm-code** [comment]
Thanks for the report :+1: Could you do me a favor and post the full console output up to the crash please?

**Comment by rm-code** [comment]
I wasn't able to reproduce this on macOS, so it seems to be a Windows specific error.

Tracked it down to:
https://github.com/rm-code/On-The-Roadside/blob/develop/src/characters/body/BodyFactory.lua#L81

Maybe a problem with how the path is put together or the TGFParser itself.

**Comment by rm-code** [comment]
@Borkason Should be working fine now.
